### PR TITLE
fix!: LONG_RUNNING_IGNORE_LIST was ignored; now an array and other smaller fixes

### PR DESCRIPTION
**Pull request by ypid**
I am OK with MIT. Ref: #2

Cc: @madeng

### CODE REVIEW

**Comment by Nanoseb** [comment]
Thanks a lot for your contribution!
I am not a tmux user, but I don't get the same output when running:
```bash
$ tmux display-message -p '#W'
zsh
```
and 

```bash
$ tmux display-message -p '#{window_id}'
@0
```
and same for `#S` and `#{session_id}` (output `0` vs `$0`).

Is it expected?

**Comment by Nanoseb** [comment]
Actually, nevermind, after reading up a bit it seems to be all fine. Just a difference between `window_name` and `window_id`, same with session, the id being likely more robust, it's all good.
Thanks again for your contribution

**Comment by ypid** [comment]
Seems you slipping into the role as maintainer. Thanks for doing/continuing this! Maintainers deserve the gratitude.

I used small git commits to make reviewing my changes transparent. I first changed to readable variable names in e81f30332eded06e0c9cbf2296ac8eae9c4b56f3 and then actually changed to from names to IDs in 29ef89074a0dfb8d73e49d02b746b32e74f8e102. The impact of each commit is specified by https://www.conventionalcommits.org/en/v1.0.0/ :)

**Comment by Nanoseb** [comment]
ah yes, indeed, read them too quickly. 
And thx for the conventional commits link, 1st time I hear about it, that looks interesting.

**Pull request merged**
